import { Order } from './../models/order.model';
const products = '/products';
export enum APP_ROUTES {
  HOME = '/home',
  PRODUCTS = products,
  PRODUCT_DETAILS = products,
  MEN_PERFUME = products + '?category=perfum&gender=male',
  WOMEN_PERFUME = products + '?category=perfum&gender=female',
  SKIN_CARE = products + '?category=skin_care',
  HAIR_CARE = products + '?category=hair_care',
  WriteReview = '/write-review',
  SignIn = '/login',
  SignUp = '/signup',
  AUTH = '/auth',
  AUTH_LOGIN = '/auth/login',
  AUTH_SIGNUP = '/auth/signup',
  DASHBOARD = '/dashboard',
  SETTINGS = '/settings',
  SHOP = '/shop',
  BLOGS = '/blogs',
  Cart = '/cart',
  CheckOut = '/checkout',
  CheckoutSuccess = '/checkout-success',
  CheckoutFailure = '/checkout-failure',
  CheckoutDirect = '/checkout-direct',
  Orders = '/orders',
  OrderDetails = '/order-details',
  Invoices = '/invoices',
  InvoiceDetails = '/invoices',
  InvoicesCreate = '/invoices-create',
  Vouchers = '/vouchers',
  VoucherDetails = '/voucher-details',
  VoucherCreate = '/voucher-create',
  About = '/about',
  Contact = '/contact',
  ReturnPolicy = '/return-policy',
  PrivacyPolicy = '/privacy-policy',
  AddAddress = '/add-address',
  EditAddress = '/edit-address',
  Addresses = '/addresses',
  AddressDetails = '/address-details',

  Favorites = '/favorites',

  Profile = '/profile',
  ProfileDetails = '/profile/details',
  ProfileEdit = '/profile/edit',
  ProfileOrders = '/profile/orders',
  ProfileAddresses = '/profile/addresses',
  ProfileFavorites = '/profile/favorites',

  Services = '/services',

  NOT_FOUND = '**',
}
